# Generated by Django 5.1.1 on 2024-09-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageproduct_product', to='store.product')),
            ],
            options={
                'verbose_name': 'ImageProduct',
                'verbose_name_plural': 'ImageProducts',
                'db_table': 'ImageProduct',
            },
        ),
    ]
